# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 18:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('beltexamapp', '0002_traveler'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='traveler',
            managers=[
                ('travelerManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
